/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => QuickMatrix
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var QuickMatrix = class extends import_obsidian.Plugin {
  async onload() {
    this.addCommand({
      id: "bracket-matrix",
      name: "Bracket matrix",
      editorCallback: async (editor) => {
        await this.new_matrix("bmatrix", editor);
      }
    });
    this.addCommand({
      id: "determinant-matrix",
      name: "Determinant Matrix",
      editorCallback: async (editor) => {
        await this.new_matrix("vmatrix", editor);
      }
    });
  }
  async new_matrix(type, editor) {
    let rowCount = Number(await new StringModal(this.app, "How many rows would you like?").openAndGetValue());
    let outputString = "$\\begin{".concat(type).concat("}");
    for (let row = 0; row < rowCount; row++) {
      let rowInput = await new StringModal(this.app, "Entries for the next row (seperated by spaces):").openAndGetValue();
      let entries = rowInput.split(" ");
      let rowString = "";
      for (let entryNo = 0; entryNo < entries.length; entryNo++) {
        rowString = rowString.concat(entries[entryNo]);
        rowString = rowString.concat("&");
      }
      rowString = rowString.substring(0, rowString.length - 1);
      rowString = rowString.concat("\\\\");
      outputString = outputString.concat(rowString);
    }
    outputString = outputString.concat("\\end{").concat(type).concat("}$");
    editor.replaceRange(outputString, editor.getCursor());
  }
};
var StringModal = class extends import_obsidian.Modal {
  constructor(app, title) {
    super(app);
    this.isFirst = true;
    this.setTitle(title);
    this.textInput = this.contentEl.createEl("input", { attr: { type: "text", size: 58 } });
  }
  openAndGetValue() {
    return new Promise((resolve) => {
      this.textInput.addEventListener("keyup", (event) => {
        if (this.isFirst) {
          this.isFirst = false;
          return;
        }
        if (event.key == "Enter") {
          resolve(this.textInput.value);
          this.close();
        }
      });
      this.open();
    });
  }
};


/* nosourcemap */